### ISSUE TITLE
Python error on fresh install

### ISSUE THREAD

**Issue by ikidd** [donaldzou/WGDashboard#132]
Freshly installed Ubuntu 20.04.  get error `configparser.NoSectionError: No section: 'Server'`

If you don't run `wgd.sh start` before you run `wgd.sh debug` you don't get a `wg-dashboard.ini` file and it fails.  This file should probably get created on `wgd.sh install`

Also: the requirement for `apt install python3-venv` might be a bit more obviously pointed out in the installation instructions than simply as a note in the venv section of the install script.

In the installation instructions the line for git clone includes a `-b v3.0` that I think isn't the case anymore, if it ever was.

**Comment by donaldzou** [comment]
Hi, thank you so much for pointing it out!! I completely forgot to put the `init_dashboard()` function for the debug mode, that's why it caused the bug. I will put a update as soon as possible. Regarding to the `venv`, some user pointed out to use it for better control on python packages, but soon i realized that Debian/Ubuntu user need to install it with `apt-get install`, rather than just work out of the box, so i just kept the code in the script and without using it.

**Comment by donaldzou** [comment]
This issued has been fixed in the latest release ;)
