### ISSUE TITLE
Memory leak in a IPv6 configuration

### ISSUE THREAD

**Issue by tokon2000** [donaldzou/WGDashboard#151]
If the server is configured with IPv6, adding a peer causes a memory leak.
The used memory is growing and growing until the system is out of memory and OOM killer is killing python3.

If I comment this part out, the memory leak is gone. So something must be wrong with getting a list of available IPs in case IPv6 is used:
https://github.com/donaldzou/WGDashboard/blob/f9dc9ebdb3e4722e2819be817114c335eaa074b1/src/dashboard.py#L582

OS: Debian 10+11

**Comment by donaldzou** [comment]
Hi! Thank you for bringing this up. I guess is when I try to parse the IP and it won't able to parse IPv6 so it caused the memory leak, or maybe is because of the [`import ipaddress`] (https://github.com/donaldzou/WGDashboard/blob/f9dc9ebdb3e4722e2819be817114c335eaa074b1/src/dashboard.py#L9) library itself.

**Comment by donaldzou** [comment]
#167
