### ISSUE TITLE
V4 feedback 

### ISSUE THREAD

**Issue by barryboom** [donaldzou/WGDashboard#290]
**Describe The Problem**
few minor issues which should be easy to fix 

1. the download instructions on the V4 branch have v4.0 which does not exist and fails to download correct versioning seems to be v4
![V4 feedback2](https://github.com/user-attachments/assets/01c40061-c480-4401-a7a1-e108b1cd5442)
2. You have missed a d the advice message under peer remote endpoint in setting should read "changed" currently reads "change"

![V4 feedback](https://github.com/user-attachments/assets/44eac53c-8290-40c5-a614-66277e5f68b3)

and a few which might not be just as easy 

1. noticed that the option to enable MFA/2FA is only available at initial setup and account creation but does not seem to be possible after this stage within settings.
2. creating a new peer does not auto fill with an available IP address which it did previously seems a backward step there or more complex than needs to be if by design.
![image](https://github.com/user-attachments/assets/aebfea40-8078-4425-a122-7788fa0ddeb9)
3. create new configuration i had issues with this on old dashboard as well, Creates but does not function and switches off after reboot. Not sure if this is just for me but i need to install the secondary config via the WG script for it to work properly.
![image](https://github.com/user-attachments/assets/4a0929ee-0426-4165-abdb-cc0545c3e906)
4. Auto start after reboot no longer seems to work either and needs to be manually started from terminal.

Other wise so far looks pretty good and sounds like a very nice list of improvements in the pipe line.

**OS Information:**
 - OS: [e.g. Ubuntu 18.02] 24.04
 - Python Version: [e.g v3.7] latest

**Comment by donaldzou** [comment]
Hi! Thank you for the feedback and I loved them!! The `v4` in the doc is intended so I don't forget to change in the official release. 

Regarding 
> Auto start after reboot no longer seems to work either and needs to be manually started from terminal.

do you mean by using the `.service` file? I will test it and get back to you :)

**Comment by bkeenke** [comment]
![image](https://github.com/user-attachments/assets/0f688e48-4aff-4b5f-bf34-76d6499f76ca)

cannot authorize using login and password admin:admin

**Comment by donaldzou** [comment]
> cannot authorize using login and password admin:admin

Hi @bkeenke, could you please check if there are any errors in `debug` mode or under console in your browser?

**Comment by bkeenke** [comment]
> > cannot authorize using login and password admin:admin
> 
> Hi @bkeenke, could you please check if there are any errors in `debug` mode or under console in your browser?

In debug mode in the browser console:
The "authToken" cookie does not have a valid "SameSite" attribute value defined. Soon, cookies without the "SameSite" attribute or with an incorrect value for this attribute will be considered "Lax". This means that cookies will no longer be sent to external contexts. If your application depends on this Cookie being available in any contexts, add a "SameSite=None" attribute label to it. To learn more about the "SameSite" attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.
The problem was due to the fact that I logged in through a mobile phone, Safari, through a PC everything was fine, there was this warning in the registration window.

![изображение](https://github.com/user-attachments/assets/38d363ae-533b-4ed2-86f5-ae430fd4e8b0)
When adding a new configuration, if the address already exists, it does not allow you to change it, you have to reload the page,
same with the port


![изображение](https://github.com/user-attachments/assets/98e7609e-e272-4119-9890-1e9d497b743c)
I created wg0 but when I start it says that it already exists

**Comment by bkeenke** [comment]
![изображение](https://github.com/user-attachments/assets/3547d851-6018-40f3-89e6-9857229ae2e3)
I deleted and wanted to recreate wg0, but when I start it says “Already have a configuration with the name "wg0"”

**Comment by donaldzou** [comment]
Hi @bkeenke, it seems like you turned on `wg0` and somehow the configuration is not `/etc/wireguard` hence why you're able to create one. Mind if I ask how did you access the dashboard? Do you have any proxy in between the browser and the dashboard?

**Comment by donaldzou** [comment]
Will close this issue for @barryboom since I finished fixing issue brought up in the first comment 🎉  and will move the issue for @bkeenke an an individual ticket.

**Comment by bkeenke** [comment]
> Hi @bkeenke, it seems like you turned on `wg0` and somehow the configuration is not `/etc/wireguard` hence why you're able to create one. Mind if I ask how did you access the dashboard? Do you have any proxy in between the browser and the dashboard?

No, I just launched the dashboard on the test server
