### ISSUE TITLE
Schedule Jobs 

### ISSUE THREAD

**Issue by hadi-dindar** [donaldzou/WGDashboard#327]
hello dear friends
i add a Schedule Jobs rule for limit data  a peers but not restrict peer

for example i add 4GB total data rule for a peer . but peer now used 5Gb data and not limited yet 

![Screenshot 2024-08-22 115646](https://github.com/user-attachments/assets/59c645de-bd78-40cf-bafe-28bc46f995cb)
![Screenshot 2024-08-22 115745](https://github.com/user-attachments/assets/bf8cd5ed-910b-4e5c-b4cf-99771fbde616)

**Comment by mohamadkazemt** [comment]
I have the same problem
The same problem exists in the time and date section

**Comment by donaldzou** [comment]
Hi all, I have to admit it is a bit confusing, and I should just leave the only option of "larger than" in the function. The reason is this:

There is a background function run every 3 minutes to check if any job is satisfied and it will execute it, so this means is nearly impossible to match a peer's data or a date when using `equal`, since the background function is not running every seconds. **I would suggest you use `larger than`, so this will match all the rules.** Sorry about the confusion

**Comment by DaanSelen** [comment]
May I ask for what reason a 3 minute interval is set?

**Comment by donaldzou** [comment]
> May I ask for what reason a 3 minute interval is set?

Not really a reason lol, I picked it cuz I feels like it won't overwhelm the server too much if we have tons of jobs, but still frequent enough :)

**Comment by donaldzou** [comment]
I'm thinking to add a field in the dashboard settings to allow users change it

**Comment by DaanSelen** [comment]
> I'm thinking to add a field in the dashboard settings to allow users change it

Sounds good!

**Comment by DaanSelen** [comment]
If you need to change it looks like line 2173 in `dashboard.py` with `            time.sleep(180)`.
